### ISSUE TITLE
How to get shared posts data from instagram direct message

### ISSUE THREAD

**Issue by tonystark262** [jstolpe/blog_code#10]
Thanks for the great series of posts which has helped me build my application. 

Currently I am trying to get messages sent from someone else to my account and I am following the [conversation endpoints](https://developers.facebook.com/docs/messenger-platform/conversations#get-information-about-a-message).

When I retrieve data using the [message endpoint](https://developers.facebook.com/docs/graph-api/reference/v19.0/message), the text message gets retrieved correctly but if the user shared a post, i cannot access that. I am able to get the link to the media of the post (only the first media). My sample output looks like

```
{
    "id": "{MESSAGE-ID}",
    "created_time": "TIME",
    "from": {
        "username": "USER",
        "id": "ID"
    },
    "to": {
        "data": [
            {
                "username": "USER2",
                "id": "ID2"
            }
        ]
    },
    "message": "SOME-MESSAGE",
    "shares": {
        "data": [
            {
                "link": "https://lookaside.fbsbx.com/ig_messaging_cdn/?asset_id=18013607600097500&signature=AbytB04ZXXPYim34RYnSUHN4WBasyNLqUhApEUHmlXuBK1PxhQ3ZdtcNodg_bjc-y89DqpQscfWsf-TwPFN5g8h7dSFFhGtt2UxPaZroe8RKHzVG6F3hH-pUUSxu6u5SvPCxqR0_OCImDzAiIsyCZrvsOYxiIGHeVQk9tw28CQWIwgjyOw9-QWq3h50y68YHm1-WWYil7cRgkibVEQDRpUJZvlxwitY"
            }
        ],
        "paging": {
            "cursors": {
                "before": "MAZDZD",
                "after": "MAZDZD"
            },
            "next": "https://graph.facebook.com/v19.0/{MESSAGE-ID}&fields=id%2Clink&limit=25&after=MAZDZD"
        }
    }
}
```

My input url and params are
```
URL: 
https://graph.facebook.com/v19.0/MESSAGE-ID

Endpoint Params: 
{
    "access_token": "PAGE_ACCESS_TOKEN",
    "fields": "id,created_time,from,to,message,reactions,attachments,shares{id,link},is_unsupported,tags,story"
}

```

Do you have an idea if it is possible to get the public post id shared with my account in direct message instead of just getting the link?

**Comment by jstolpe** [comment]
Hey and thanks for checking out my videos! From what I can tell you can't get the public post id.
