### ISSUE TITLE
Undefined index: paging

### ISSUE THREAD

**Issue by danieladi050** [jstolpe/blog_code#2]
hello, i have watch several great video instsagram basic display api and your video is one of the best. i find this error Undefined index: paging in ... line 171 i believe. and it happen to be in the call api function. when i copy your code from github and run it in my host ( i use 000webhost ) i think it happen because the your $params has alot of different structure for example it have different structure in function getusermedia ( dont have paging ) and getpaging (only have paging ) but both of the function use call api function. thats why the paging is undefined. this is only my hypothesis so do you have any suggestion ?

**Comment by pgroot91** [comment]
Noticed this as well

**Comment by jstolpe** [comment]
Yeah this is the issue.
